ARG DIFY_WEB_VERSION=1.11.4
FROM langgenius/dify-web:${DIFY_WEB_VERSION}

# Override default Dify logos with custom ones
COPY logo.svg /app/web/public/logo/logo.svg
COPY logo-monochrome-white.svg /app/web/public/logo/logo-monochrome-white.svg
